"use client";

import React, { useState } from "react";
import Link from "next/link";
import { Github, Sparkles, ShieldCheck, ArrowRight, Zap, CheckCircle2 } from "lucide-react";

interface EmptyStateProps {
  onLoadDemo?: () => Promise<void>;
}

export function DashboardEmptyState({ onLoadDemo }: EmptyStateProps) {
  const [loadingDemo, setLoadingDemo] = useState(false);

  const handleDemoClick = async () => {
    if (loadingDemo) return;
    setLoadingDemo(true);
    try {
      if (onLoadDemo) {
        await onLoadDemo();
      } else {
        // Trigger GitHub connect fallback
        window.location.href = "/api/github/connect?installation_id=999999";
      }
    } catch (err) {
      console.error("Error loading demo:", err);
      setLoadingDemo(false);
    }
  };

  return (
    <div className="glass-card rounded-3xl p-10 md:p-14 border border-white/10 relative overflow-hidden text-center max-w-4xl mx-auto shadow-2xl">
      {/* Background Glow & Mesh */}
      <div className="absolute -top-24 left-1/2 -translate-x-1/2 h-64 w-96 bg-gradient-to-r from-indigo-500/20 via-purple-500/20 to-pink-500/20 rounded-full blur-3xl pointer-events-none"></div>

      {/* Top Icon Badge */}
      <div className="inline-flex items-center justify-center p-4 rounded-2xl bg-gradient-to-br from-indigo-500/20 to-purple-600/20 border border-indigo-500/30 text-indigo-400 mb-6 shadow-glow">
        <ShieldCheck className="h-10 w-10 animate-pulse" />
      </div>

      {/* Heading & Value Prop */}
      <h2 className="text-3xl md:text-4xl font-extrabold text-white mb-4 tracking-tight">
        Connect Your First <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 via-purple-400 to-pink-400">AI-Built Codebase</span>
      </h2>
      <p className="text-base text-slate-300 max-w-2xl mx-auto mb-8 leading-relaxed">
        VibeAudit continuously audits repositories generated by Cursor, v0, Bolt, and Lovable. We catch subtle logic bugs, security leaks, and zero-days—then autonomously open GitHub PRs to fix them.
      </p>

      {/* Features Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 max-w-3xl mx-auto mb-10 text-left">
        <div className="p-4 rounded-2xl bg-white/[0.02] border border-white/5 flex items-start gap-3">
          <div className="p-2 rounded-lg bg-emerald-500/10 text-emerald-400 mt-0.5 shrink-0">
            <CheckCircle2 className="h-4 w-4" />
          </div>
          <div>
            <h4 className="text-xs font-bold text-white mb-1">Zero-Day AI Detection</h4>
            <p className="text-[11px] text-slate-400">Identifies flawed AI patterns before going to production.</p>
          </div>
        </div>
        <div className="p-4 rounded-2xl bg-white/[0.02] border border-white/5 flex items-start gap-3">
          <div className="p-2 rounded-lg bg-indigo-500/10 text-indigo-400 mt-0.5 shrink-0">
            <Sparkles className="h-4 w-4" />
          </div>
          <div>
            <h4 className="text-xs font-bold text-white mb-1">Autonomous Fix PRs</h4>
            <p className="text-[11px] text-slate-400">Generates clean, tested code fixes directly to your GitHub.</p>
          </div>
        </div>
        <div className="p-4 rounded-2xl bg-white/[0.02] border border-white/5 flex items-start gap-3">
          <div className="p-2 rounded-lg bg-purple-500/10 text-purple-400 mt-0.5 shrink-0">
            <Zap className="h-4 w-4" />
          </div>
          <div>
            <h4 className="text-xs font-bold text-white mb-1">24/7 Webhook Audit</h4>
            <p className="text-[11px] text-slate-400">Scans every git push in background without slowing dev speed.</p>
          </div>
        </div>
      </div>

      {/* Primary Action Buttons */}
      <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
        <Link
          href="/onboarding"
          className="w-full sm:w-auto flex items-center justify-center gap-3 rounded-2xl bg-gradient-to-r from-indigo-500 via-purple-600 to-pink-500 px-8 py-4 font-bold text-white shadow-glow hover:opacity-95 transition-all duration-200 text-sm group"
        >
          <Github className="h-5 w-5 fill-current" />
          <span>Connect GitHub App</span>
          <ArrowRight className="h-4 w-4 group-hover:translate-x-1 transition-transform" />
        </Link>

        <button
          onClick={handleDemoClick}
          disabled={loadingDemo}
          className="w-full sm:w-auto flex items-center justify-center gap-2.5 rounded-2xl bg-white/[0.05] hover:bg-white/[0.1] border border-white/10 px-7 py-4 font-semibold text-slate-200 hover:text-white transition-all duration-200 text-sm"
        >
          {loadingDemo ? (
            <>
              <span className="h-4 w-4 border-2 border-white/30 border-t-white rounded-full animate-spin"></span>
              <span>Loading Demo Codebase...</span>
            </>
          ) : (
            <>
              <Sparkles className="h-4 w-4 text-purple-400" />
              <span>Load Demo $100K SaaS Repo</span>
            </>
          )}
        </button>
      </div>
    </div>
  );
}
